name: Day2-Demo
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello Action"

      - name: say goodbay
        run: echo "goodbay"
        
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: update system
        run: sudo apt update
      - name: Date & time
        run: uptime
        
  
